// <auto-generated />
namespace EFCar2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Tulaj_hozzaadasa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tulaj_hozzaadasa));
        
        string IMigrationMetadata.Id
        {
            get { return "202002261356277_Tulaj_hozzaadasa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
