// <auto-generated />
namespace EFCar2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class tipus_hozzaadas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tipus_hozzaadas));
        
        string IMigrationMetadata.Id
        {
            get { return "202002261349343_tipus_hozzaadas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
