// <auto-generated />
namespace EFCarMigration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class rendszam_hozzaadas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(rendszam_hozzaadas));
        
        string IMigrationMetadata.Id
        {
            get { return "202002181708390_rendszam_hozzaadas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
